/** Unique temperature notes. One sentence each. No shared default. */
export const COMPAT_NOTES = {
  "ada-vale": "0.3 keeps her in the war room. Higher and she writes essays about coupling.",
  "kenji-okada": "Low enough that he asks for the estimand before he designs the trial.",
  "maris-thorne": "Keep it cool so she dates the claim instead of narrating the century.",
  "elena-voss": "If she starts performing courtroom, drop it. She should write the other table first.",
  "samir-haddad": "Stay conservative. This persona must not drift into diagnosis.",
  "priya-raman": "Low-middle. She should reach for a payoff table, not a TED story.",
  "jonah-reed": "If the non-goal disappears from the answer, you went too high.",
  "nia-okonkwo": "Keep it tight. Threat models get sloppy when the temperature is decorative.",
  "tomas-rios": "He should still mention water and the maintenance truck. If not, lower it.",
  "rhea-cole": "Low. She prints nothing she cannot source.",
  "devin-cho": "If he starts slogan-ing labor, drop it. He should rewrite the worker's next-best option.",
  "amara-singh": "Keep it boundaried. Warmth is allowed; therapy-cosplay is not.",
  "helena-park": "Low. Claim language, not courtroom theater.",
  "malik-bennett": "He should name the objective the room will fire someone over. If he gets polite, lower it.",
  "freya-lind": "Split physics from scenario. If the split vanishes, the temperature is too high.",
  "sofia-alvarez": "She should still walk the corner at 8:15 p.m. If not, cool it.",
  "victor-lang": "Ask for the bank statement. If he starts sounding like a pitch deck, lower it.",
  "mei-zhou": "She should ask what the vehicle does when the computer is wrong.",
  "harlan-webb": "Force the mode of argument. If he lectures constitutional lore, drop it.",
  "nadia-farouk": "Rewrite the headline with a denominator. That move should survive any temperature.",
  "lila-moreau": "If she outlines instead of rewriting a paragraph, you went too high.",
  "haruto-shin": "He should return a hero frame, not a mood board. Lower if the adjectives come back.",
  "calder-finch": "Keep the refrain. If he writes a novel, cool it.",
  "iseult-byrne": "She should scan the line. If she only talks about flow, drop the temperature.",
  "marcus-hale": "The last line should be a behavior. If it becomes a speech, lower it.",
  "june-ellis": "Kill the lyrical headline. If she starts sounding like the brand, cool it.",
  "kade-morrow": "Room, verb, one line. If you get a lore essay, the temperature is wrong.",
  "rio-vance": "One mute, one lift. If he stacks metaphors, lower it.",
  "anya-solis": "She should refuse the trailer-shaped lie. Keep her there.",
  "simone-roux": "Physical sensation, then whether the dish deserved it. No empty raves.",
  "peck-dunne": "Split line and grip. If he blesses a render, you went too high.",
  "nell-bright": "The child should still get to do something. If the ending preaches, lower it.",
  "silas-kane": "Stay near 0.4. Higher and he starts enjoying the con more than naming it.",
  "solenne-march": "Constraint first, then paths. If she cheers, drop it.",
  "attalus": "He should return what is theirs and what is yours. No stoic poster.",
  "puck": "0.95 is the point. Harvest keepers or the heat was a waste.",
  "harrington": "If the courtesy swallows the ask, lower it.",
  "ellis-crowe": "He should ask for the methods section, not burn the library.",
  "hollis": "Keep it low. If he starts explaining why he is brief, you went too high.",
  "wren-plan": "Lists, owners, two contingencies. If she pep-talks, cool it.",
  "aunt-lin": "Kitchen-table, not therapist. If she diagnoses, drop it.",
  "holt-steel": "Other side first. If he dunks, the temperature is wrong.",
  "moss-explain": "Three layers, then the lie in the picture. Don't let him quiz.",
  "cora-flint": "If she starts writing pep instead of a clock, drop the temperature.",
  "evander": "The cut should leave a quieter thing standing. If he performs melancholy, lower it.",
  "briggs": "In their corner, not a speechwriter for the institution.",
  "the-midwife": "One question. If she lectures, you went too high.",
  "cross-debate": "Concede what is lost. If it becomes a dunk, lower it.",
  "mira-sol": "One conversation with one person. Strategy as a visible act.",
  "ash-denning": "Alternative hypothesis, then the indicator. No feature writing.",
  "the-cartographer": "Factions that already wanted something. Players are the twist.",
  "rook": "Twenty-second stake, one follow-up they are not ready for.",
  "quinn-ibarra": "One decision sentence. Park everything pretending to be that sentence.",
  "the-diff": "Live in the hunk. If it redesigns the platform, you picked the wrong voice.",
  "celeste-ward": "Aims a reviewer can score. No minted preliminary data.",
  "rita-solano": "Task title, then steps. If the adjectives return, lower it.",
  "orion-7": "If the elegy crowds out the triage list, lower temperature.",
  "ms-quill": "No minted shelfmarks. If she forges a pamphlet, the run is broken.",
  "grit": "Lower if the goblin gets riffy and stops reading the code.",
  "night-frequency": "0.7 is the late show. Drop it if the host starts inventing a city.",
  "tess-rowan": "If the week does not have three named owners, lower it.",
  "boone-keller": "First sentence should not paste onto another company.",
  "nyla-shore": "A dated mutual next step, or a walk. If she chats, cool it.",
  "ivo-grant": "Behavior first. If he starts delighting, drop it.",
  "sable-ortiz": "Four-line answer, then the macro. No apology essays.",
  "dara-pell": "Offer and kill date. If she writes a manifesto, lower it.",
  "lev-anders": "Ask for the bank number. If he forecasts from a vibe, drop it.",
  "yara-bloch": "Scorecard with evidence. No rockstar language.",
  "oren-pike": "Trigger, owner, done. If he writes a binder, cool it.",
  "cass-elwood": "The true date in sentence one.",
  "jude-harlow": "Stage tests, then the number that survives.",
  "noor-velez": "Labels first. Three drafts max.",
  "pax-drummond": "Ask about export and the renewal trap.",
  "enid-shaw": "A price a stranger can repeat, plus a written exception.",
  "remy-gale": "Findings with n. No invented quotes.",
  "kit-brant": "Spec with a human on the failure path, or a no.",
};
